#SPDX-License-Identifier: MIT-0
---
- name: apache2 restart
  ansible.builtin.service:
    name: apache2
    state: restarted
    enabled: yes

- name: apache2 reload
  ansible.builtin.service:
    name: apache2
    state: reloaded
    enabled: yes

